spring:
  profiles:
    include:
      - core
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
  security:
    user:
      name: jaeho
      password: 3145

server:
  error:
    include-message: always
  port: 8080
---
