spring:
  flyway:
    enabled: false
---
spring:
  profiles: local
  datasource:
    platform: h2
    url: jdbc:h2:~/test;AUTO_SERVER=TRUE
    hikari:
      username: sa
  jpa:
    open-in-view: true
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database: h2

---